/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.action;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.StringTokenizer;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

 
import com.bean.ComBean;
import com.util.Constant; 

/** 
 * MyEclipse Struts
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ComAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
			request.setCharacterEncoding("gb2312");
		} catch (Exception ex) {
			// TODO Auto-generated catch block
			ex.printStackTrace();
		}	
		String strr="";
		try{
			String date=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
			String date2=new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
			String method=request.getParameter("method").trim();
			ComBean cBean = new ComBean();
			HttpSession session = request.getSession();   
			if(method.equals("addjxj")){ //登记奖学金  ---代码注释 
				String zt = request.getParameter("zt");  
				String dj = request.getParameter("dj");   
				String ly = request.getParameter("ly");  
				String sm = request.getParameter("sm");  
				String member=(String)session.getAttribute("member"); 
				String xm=cBean.getString("select realname from member where username='"+member+"'"); 
				String bj=cBean.getString("select sex from member where username='"+member+"'"); 
				 
				int flag=cBean.comUp("insert into jxj(zt,dj,ly,sm,member,xm,bj,tjsj,xsp,xyj,xld,ysp,yyj,yld,spjg,ch) " +
						"values('"+zt+"','"+dj+"' ,'"+ly+"','"+sm+"' ,'"+member+"', '"+xm+"', '"+bj+"', '"+date2+"','暂无','暂无','暂无','暂无','暂无','暂无','暂无','否') ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/jxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/jxj/index.jsp").forward(request, response); 
				}  
			}
			else if(method.equals("upjxj")){  //修改奖学金
				String id = request.getParameter("id");  
				String zt = request.getParameter("zt");  
				String dj = request.getParameter("dj");   
				String ly = request.getParameter("ly");  
				String sm = request.getParameter("sm");  
				String member=(String)session.getAttribute("member"); 
				String xm=cBean.getString("select realname from member where username='"+member+"'"); 
				String bj=cBean.getString("select sex from member where username='"+member+"'"); 
				int flag=cBean.comUp("update jxj set zt='"+zt+"',dj='"+dj+"',ly='"+ly+"' ,sm='"+sm+"',xm='"+xm+"',bj='"+bj+"'  where id='"+id+"'");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/jxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/jxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("chjxj")){  //修改奖学金
				String id = request.getParameter("id"); 
				int flag=cBean.comUp("update jxj set ch='是'  where id='"+id+"'");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/jxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/jxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("chjxj2")){  //修改奖学金
				String id = request.getParameter("id"); 
				int flag=cBean.comUp("update jxj set ch='否'  where id='"+id+"'");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/jxj/ch.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/jxj/ch.jsp").forward(request, response); 
				}
			}
			else if(method.equals("deljxj")){  //删奖学金
				String id = request.getParameter("id");   
				int flag=cBean.comUp("delete from jxj where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/jxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/jxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("addzxj")){ //登记助学金  ---代码注释 
				String zt = request.getParameter("zt");  
				String dj = request.getParameter("dj");   
				String ly = request.getParameter("ly");  
				String sm = request.getParameter("sm");  
				String member=(String)session.getAttribute("member"); 
				String xm=cBean.getString("select realname from member where username='"+member+"'"); 
				String bj=cBean.getString("select sex from member where username='"+member+"'"); 
				 
				int flag=cBean.comUp("insert into zxj(zt,dj,ly,sm,member,xm,bj,tjsj,xsp,xyj,xld,ysp,yyj,yld,spjg,ch) " +
						"values('"+zt+"','"+dj+"' ,'"+ly+"','"+sm+"' ,'"+member+"', '"+xm+"', '"+bj+"', '"+date2+"','暂无','暂无','暂无','暂无','暂无','暂无','暂无','否') ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/zxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/zxj/index.jsp").forward(request, response); 
				}  
			}
			else if(method.equals("upzxj")){  //修改助学金
				String id = request.getParameter("id");  
				String zt = request.getParameter("zt");  
				String dj = request.getParameter("dj");   
				String ly = request.getParameter("ly");  
				String sm = request.getParameter("sm");  
				String member=(String)session.getAttribute("member"); 
				String xm=cBean.getString("select realname from member where username='"+member+"'"); 
				String bj=cBean.getString("select sex from member where username='"+member+"'"); 
				int flag=cBean.comUp("update zxj set zt='"+zt+"',dj='"+dj+"',ly='"+ly+"' ,sm='"+sm+"',xm='"+xm+"',bj='"+bj+"'  where id='"+id+"'");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/zxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/zxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("chzxj")){  //修改助学金
				String id = request.getParameter("id"); 
				int flag=cBean.comUp("update zxj set ch='是'  where id='"+id+"'");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/zxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/zxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("chzxj2")){  //修改助学金
				String id = request.getParameter("id"); 
				int flag=cBean.comUp("update zxj set ch='否'  where id='"+id+"'");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/zxj/ch.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/zxj/ch.jsp").forward(request, response); 
				}
			}
			else if(method.equals("delzxj")){  //删助学金
				String id = request.getParameter("id");   
				int flag=cBean.comUp("delete from zxj where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/zxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/zxj/index.jsp").forward(request, response); 
				}
			}
			
			
			else if(method.equals("adddk")){ //登记贷款  ---代码注释 
				String zt = request.getParameter("zt");  
				String dj = request.getParameter("dj");   
				String ly = request.getParameter("ly");  
				String sm = request.getParameter("sm");  
				String member=(String)session.getAttribute("member"); 
				String xm=cBean.getString("select realname from member where username='"+member+"'"); 
				String bj=cBean.getString("select sex from member where username='"+member+"'"); 
				 
				int flag=cBean.comUp("insert into dk(zt,dj,ly,sm,member,xm,bj,tjsj,xsp,xyj,xld,ysp,yyj,yld,spjg,ch) " +
						"values('"+zt+"','"+dj+"' ,'"+ly+"','"+sm+"' ,'"+member+"', '"+xm+"', '"+bj+"', '"+date2+"','暂无','暂无','暂无','暂无','暂无','暂无','暂无','否') ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/dk/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/dk/index.jsp").forward(request, response); 
				}  
			}
			else if(method.equals("updk")){  //修改贷款
				String id = request.getParameter("id");  
				String zt = request.getParameter("zt");  
				String dj = request.getParameter("dj");   
				String ly = request.getParameter("ly");  
				String sm = request.getParameter("sm");  
				String member=(String)session.getAttribute("member"); 
				String xm=cBean.getString("select realname from member where username='"+member+"'"); 
				String bj=cBean.getString("select sex from member where username='"+member+"'"); 
				int flag=cBean.comUp("update dk set zt='"+zt+"',dj='"+dj+"',ly='"+ly+"' ,sm='"+sm+"',xm='"+xm+"',bj='"+bj+"'  where id='"+id+"'");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/dk/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/dk/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("chdk")){  //修改贷款
				String id = request.getParameter("id"); 
				int flag=cBean.comUp("update dk set ch='是'  where id='"+id+"'");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/dk/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/dk/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("chdk2")){  //修改贷款
				String id = request.getParameter("id"); 
				int flag=cBean.comUp("update dk set ch='否'  where id='"+id+"'");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/dk/ch.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/dk/ch.jsp").forward(request, response); 
				}
			}
			else if(method.equals("deldk")){  //删贷款
				String id = request.getParameter("id");   
				int flag=cBean.comUp("delete from dk where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("member/dk/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("member/dk/index.jsp").forward(request, response); 
				}
			}
			///////////////////////////////////////////////////////////////////////////////////////////////以下管理员操作功能
			
			
			else if(method.equals("deljxj2")){  //删奖学金
				String id = request.getParameter("id");   
				int flag=cBean.comUp("delete from jxj where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/jxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/jxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("delzxj2")){  //删助学金
				String id = request.getParameter("id");   
				int flag=cBean.comUp("delete from zxj where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/zxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/zxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("deldk2")){  //删贷款
				String id = request.getParameter("id");   
				int flag=cBean.comUp("delete from dk where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/dk/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/dk/index.jsp").forward(request, response); 
				}
			}
			//////////////院
			
			else if(method.equals("deljxj3")){  //删奖学金
				String id = request.getParameter("id");   
				int flag=cBean.comUp("delete from jxj where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/yjxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/yjxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("delzxj3")){  //删助学金
				String id = request.getParameter("id");   
				int flag=cBean.comUp("delete from zxj where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/yzxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/yzxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("deldk3")){  //删贷款
				String id = request.getParameter("id");   
				int flag=cBean.comUp("delete from dk where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/ydk/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/ydk/index.jsp").forward(request, response); 
				}
			}
			
			/////
			
			 
			
			else if(method.equals("xispjxj")){  //审批
				String id = request.getParameter("id");  
				String xsp = request.getParameter("xsp");  
				String xyj = request.getParameter("xyj");   
				String username=(String)session.getAttribute("user"); 
				int flag=cBean.comUp("update jxj set xsp='"+xsp+"',xyj='"+xyj+"',xld='"+username+"' where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/jxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/jxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("xispzxj")){  //审批
				String id = request.getParameter("id");  
				String xsp = request.getParameter("xsp");  
				String xyj = request.getParameter("xyj");   
				String username=(String)session.getAttribute("user"); 
				int flag=cBean.comUp("update zxj set xsp='"+xsp+"',xyj='"+xyj+"',xld='"+username+"' where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/zxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/zxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("xispdk")){  //审批
				String id = request.getParameter("id");  
				String xsp = request.getParameter("xsp");  
				String xyj = request.getParameter("xyj");   
				String username=(String)session.getAttribute("user"); 
				int flag=cBean.comUp("update dk set xsp='"+xsp+"',xyj='"+xyj+"',xld='"+username+"' where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/dk/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/dk/index.jsp").forward(request, response); 
				}
			}
			
			
			
			else if(method.equals("yuanspjxj")){  //审批
				String id = request.getParameter("id");  
				String ysp = request.getParameter("ysp");  
				String yyj = request.getParameter("yyj");   
				String username=(String)session.getAttribute("user"); 
				int flag=cBean.comUp("update jxj set ysp='"+ysp+"',yyj='"+yyj+"',yld='"+username+"',spjg='通过' where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/yjxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/yjxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("yuanspzxj")){  //审批
				String id = request.getParameter("id");  
				String ysp = request.getParameter("ysp");  
				String yyj = request.getParameter("yyj");   
				String username=(String)session.getAttribute("user"); 
				int flag=cBean.comUp("update zxj set ysp='"+ysp+"',yyj='"+yyj+"',yld='"+username+"',spjg='通过' where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/yzxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/yzxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("yuanspdk")){  //审批
				String id = request.getParameter("id");  
				String ysp = request.getParameter("ysp");  
				String yyj = request.getParameter("yyj");   
				String username=(String)session.getAttribute("user"); 
				int flag=cBean.comUp("update dk set ysp='"+ysp+"',yyj='"+yyj+"',yld='"+username+"',spjg='通过' where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/ydk/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/ydk/index.jsp").forward(request, response); 
				}
			}
			
			
			
			else if(method.equals("deljxj4")){  //删奖学金
				String id = request.getParameter("id");   
				int flag=cBean.comUp("delete from jxj where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/ayjxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/ayjxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("delzxj4")){  //删助学金
				String id = request.getParameter("id");   
				int flag=cBean.comUp("delete from zxj where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/ayzxj/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/ayzxj/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("deldk4")){  //删贷款
				String id = request.getParameter("id");   
				int flag=cBean.comUp("delete from dk where id='"+id+"' ");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/aydk/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/aydk/index.jsp").forward(request, response); 
				}
			}
			else{//无参数传入转到错误页面
				request.getRequestDispatcher("error.jsp").forward(request, response);
			}
		}
		catch(Exception e){
			e.printStackTrace();
			return mapping.findForward("error.jsp"); 
		}
		return mapping.findForward(strr);
	} 
}